branches:
  only:
    - masterlanguage: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
before_script:
 - chmod +x ./build.sh
script:
  - ./build.sh --quiet verify
  
after_script: # here's a build step block
- echo "We can put normal shell commands here"
- echo "more shell commands here"
